baseURL = "https://soccerdaily-alpha.vercel.app/"
languageCode = "en-us"
title = "US Daily Context"
# theme = "neo-news"
canonifyURLs = true

[permalinks]
  # Ini perintahnya: Folder 'articles' -> Linknya jadi /judul-slug/
  articles = '/:slug/'
  
[params.author]
  name = "Dave Harsya (Senior Analyst)"
  email = "contact@soccerdaily.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  
# --- BAGIAN INI SANGAT PENTING ---
[outputs]
  home = ["HTML", "RSS","Sitemap"]    # HTML Wajib di urutan pertama!
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[services.rss]
  limit = 20
  
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "AI-Powered Journalism covering US Top Stories."
  defaultImage = "/images/default-news.jpg"
